### PR TITLE
Drop all forks of forks of forks

### PR DESCRIPTION
**Pull request by rickerd**
Drop all forks of forks and work together to make a major version that has all the nice features into it.

### CODE REVIEW

**Comment by vogloblinsky** [comment]
I don't have time for this directive right now, this one is still better maintened : https://github.com/CrackerakiUA/ngImgCropFullExtended

**Comment by rickerd** [comment]
@vogloblinsky i am the contributor of the directive.
Please drop your repo so we can work on 1 big and good directive.

**Comment by vogloblinsky** [comment]
Ok, no problem. so why this PR ?

**Comment by rickerd** [comment]
I could not create an issue.. so i had to drawn your attention somehow.
Many thanks!

**Comment by vogloblinsky** [comment]
Just a mail with my email on my profile would do the same.
I drop it right now.

**Pull request closed without merging**
