### PR TITLE
Alot of updates

### PR DESCRIPTION
**Pull request by rickerd**
I think we should make 1 repo and work with forks and branches.
Its now a bit shitty because this repo + CrackerakiUA's repo are the best there is but still have diffs.

Lets work together. My last contrib. is v5.0.1 and adds the area-init-size so the cropper can have a stanard init size if the user gives it through the directive

### CODE REVIEW

**Comment by vogloblinsky** [comment]
Ok for me, is CrackerakiUA ok ?

**Comment by rickerd** [comment]
I don't know, how can we ask him @CrackerakiUA are you okay to work on this project and extend it even further.
Would be nice if the 3 of us or something have right to update the tags and stuff. Because if some of us don't has any time.. another developer could do it.

**Comment by CrackerakiUA** [comment]
If someone want to work on my fork actively i could add rights to him. I am contributing as i can on my fork. And i don't want to work on other fork, many people have been connected to mine.

**Comment by rickerd** [comment]
Okay if i understand correct:
@vogloblinsky is the starter of ngImgCropExtended and you forked it. You did a PR a while ago and Vincent didn't do anything with it.
Now you don't want to work on a fork that you don't control.

People forked your version alot, but smart developer would see that if we work on 1 ngImgCropExtended that they are commits behind.
We could use a little media attention / website to promote the correct version no matter what fork or url we're working on.

But now.. it sucks big time.

Cmon guys what is the best proposition. Who's fork are we picking / using. I wana contribute to the project (already did a bit) but its lacking a professional management.

**Comment by CrackerakiUA** [comment]
@vogloblinsky is not active, as far as i know.

**Comment by rickerd** [comment]
@vogloblinsky are okay to merge your things into @CrackerakiUA fork?
We need to do something caus 2 things isn't representable for all the developers that are using the thing.

**Comment by vogloblinsky** [comment]
Ok for me

**Comment by rickerd** [comment]
Okay can you make a PR into the other fork?
And can CrackerakiUA give me some rights? I would love to develop and help this project better and bigger, with some leveled code ofcourse.

**Comment by rickerd** [comment]
@vogloblinsky ? Can you merge you things into @CrackerakiUA his fork? From that point we can built a better version with tags and stuff.
Because the cropper is a great tool.

Thanks in advance

**Pull request merged**
